WIP: Building your own decays lesson
lhcb/second-analysis-steps pull request #44
Opened 2017-04-27 11:51 UTC by apuignav

This may end up split in several sub-lessons.

2017-04-30 22:00 UTC, apuignav commented
The lessons have changed significantly, so a few extra pairs of eyes would be nice.

2017-05-02 10:17 UTC, lcapriot requested changes
Thanks Albert! My comments:

In building-decays-part0.md
- The definition of Selection is a bit confusing. The first thing you say is that "It uses other Selections to process LHCb::Particles...". Does it make sense to say simply "It processes LHCb::Particles..." ?

In building-decays-part1.md
- dstar_sel should have d0_sel as RequiredSelection and not dstar

2017-05-02 10:22 UTC, lcapriot commented on building-decays-part1.md
> +    RequiredSelections=[dstar, Pions]
RequiredSelections=[d0_sel, Pions]

2017-05-02 16:14 UTC, apuignav commented on building-decays-part1.md
> +    RequiredSelections=[dstar, Pions]
Thanks! Added.

2017-05-03 07:22 UTC, merged